version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: database_name
    volumes:
      - db_data
